### ISSUE TITLE
Mad cats missing black cats.. 

### ISSUE THREAD

**Issue by jondor** [Ariadne-CMS/ariadne#11]
In the /system/scaffolds/muze/pproject/madcat/site/ misses the "black" folder resulting in a not working site when creating a new site based on this scaffold. Guess that's not the idea.

**Comment by poef** [comment]
I'm having trouble reproducing this, there is indeed no 'black' folder, but the site works fine without it. Which errors do you get?

**Comment by poef** [comment]
No reply, assuming it was something else.
