### ISSUE TITLE
Install php <5.6

### ISSUE THREAD

**Issue by jondor** [Ariadne-CMS/ariadne#127]
While installing Ariadne 9,7 on a pristine Linux Ubuntu 14.04.5 LTS environment I ran into serious issues in that the backend was working as it should, but the frontend refused to see anything in libraries. 
Long story short, it only works after I upgraded the PHP to 5.6.28-1 using the ondrej php5.6 PPA.
14.04.5 goes up to 5.5.9. 

As the installer checkes that everything > 5.4.7 5.5.9 was accepted as usable. 

After upgrading to 5.6 php5.6-xml and php5.6-mbstring had to be added so those should be checked for too. (mbstring is checked,  but has no help)

5.5.9 also generates loads of errors as array_filter didn't have the 3th parameter yet.

**Comment by ylebre** [comment]
We have 5.6 in travis as a baseline, so we'll probably take that as a new baseline. If you have ideas how to check for php5.6-xml in system_checks, a PR would be appreciated!

**Comment by ylebre** [comment]
fixed as part of PR #135
