### ISSUE TITLE
__clone method

### ISSUE THREAD

**Issue by jondor** [Ariadne-CMS/ariadne#129]
--->8---
Connected to weba1.enschede.nl.
220 Ariadne FTP
Name (weba1.enschede.nl:ENSC\bahoogg): admin
331 Password required for 'admin'
Password:
230 User 'admin' logged in at /
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
200 ok, connecting to 217.114.107.126 39146
150 Opening ASCII mode data connection
dr-xr-x---   1 admin    admin           0 Jun 15 09:18 [files]
dr-xr-x---   1 admin    admin           0 Jun 15 09:18 [objects]
PHP Fatal error:  Uncaught Error: __clone method called on non-object in /opt/intranet/ariadne/lib/objects/ariadne_object.php:1316
--->8---

Doesn't seem ok.. 

PHP 7.1.3-3+deb.sury.org~trusty+1 (cli) (built: Mar 25 2017 14:24:10) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3-3+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies

latest git version of Ariadne.

**Comment by poef** [comment]
Thanks, I'll take a look at it, expect a fix late next week.

**Comment by poef** [comment]
I can't reproduce it with PHP 5.6 or 7.0, have to wait for the weekend to check it on 7.1.

**Comment by jondor** [comment]
Been a search, but in the end it was due to a database error. An entry in the store_nodes where the path field was empty. Manually fixing the database solved the issue.
