### ISSUE TITLE
Missing translations?

### ISSUE THREAD

**Issue by jondor** [Ariadne-CMS/ariadne#130]
Missing translations? Freshly installed ariadne 9.7 

![editor9 7](https://user-images.githubusercontent.com/1584984/27177510-ee3034ec-51c6-11e7-8ebc-2ac11c48cf3f.PNG)

Searching for on of those strings results in nothingness:
```
root@ensc-weba2:/opt/internet/ariadne# grep -Ri 'vd_ol' *
grep: vendor/bin/lessc: No such file or directory
root@ensc-weba2:/opt/internet/ariadne#
```

**Comment by ylebre** [comment]
Could it be that an older editor.ini is used on this site? The nls key should be vd.editor:ol instead of vd_ol.
