### ISSUE TITLE
Array's apparently aren't stored in custom properties anymore

### ISSUE THREAD

**Issue by Whoeaaah** [Ariadne-CMS/ariadne#14]
A one dimensional array in a custom field (registered as property) apparently isn't saved in the 'store_prop_custom' table anymore. It used to work so that each value was saved as a field within said table. (multiple fields with the same AR_name)

**Comment by mjrider** [comment]
could you supply us with code to reproduce the problem, preferably in an ax export.
We can than reproduce the problem in different versions of Ariadne to find the  commit causing the problem.
