### ISSUE TITLE
Double clicking folder does not enter folder (Chrome)

### ISSUE THREAD

**Issue by ElephantTrail** [Ariadne-CMS/ariadne#142]
Hi,

When in Ariadne in Chrome browser, double clicking doesn't enter a folder anymore. Browsing Ariadne only works in the file tree on the left side. I'm talking about an anchor like:

`<a class="explore_link" href="explore.html" ondblclick="top.muze.ariadne.explore.view('/system/users/admin/sites/');" title="Sites"></a>`

Double clicking does nothing. How to fix? Tested in Safari, and it works there.

Thanks

**Comment by ElephantTrail** [comment]
![Hello?](https://i.pinimg.com/originals/10/2a/99/102a998252d4c30070cd4ddefac9901e.jpg)

**Comment by ylebre** [comment]
I'm not sure which version seems to be a problem, but I've tested this with the currect master branch with php7.2 and chrome 80 on a fresh install, and am not able to reproduce this. Could you check with the latest master to verify if the problem is still there? If so, please reopen this issue.
