### ISSUE TITLE
Ariadne 10 stable

### ISSUE THREAD

**Issue by ElephantTrail** [Ariadne-CMS/ariadne#143]
Hi,

When are you planning to release a stable version of Ariadne 10? The RC1 has been out for some time now.

Would like to hear, thnx.

**Comment by ylebre** [comment]
We're working on the final tests now, expecting to release it within the next couple of months. Things are moving slowly on our end - if you have time to test with the currect master and report any problems, that would be very helpful. Closing this issue for now.
