### ISSUE TITLE
MySQL version

### ISSUE THREAD

**Issue by ElephantTrail** [Ariadne-CMS/ariadne#145]
Hi,

Currently running Ariadne 9.7 with MySQL 5.5.62.
We are looking to upgrade the MySQL to the latest version available, is this Ariadne compatible? If not, what version is?

Cheers

**Comment by poef** [comment]
I believe it is, however newer mysql versions default to a stricter configuration, which isn't compatible. You can workaround it by setting the sql mode like this (command line)

`mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"`

This removes a number of default settings, specifically: ONLY_FULL_GROUP_BY, STRICT_TRANS_TABLES, NO_ZERO_IN_DATE, NO_ZERO_DATE and ERROR_FOR_DIVISION_BY_ZERO.

You can also set it for each client connection seperately and I believe its a configuration option as well. Read more at [https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sql-mode-setting](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sql-mode-setting)

regards

**Comment by ElephantTrail** [comment]
Hi @poef,

Thanks! A couple of other questions regarding our planned upgrade:

1. It seems we are running Ariadne CMS 9.5 currently. Is it possible to do a direct upgrade to 10.0RC1, or is it necessary to do it step by step, f.e. 9.5 > 9.6 > 9.7 > 10RC1?

2. What would you say is the **optimal** MySQL version for 10RC1?

3. Out of curiosity: are you running 10RC1 with PHP 7.3 of 7.4 perhaps and is it working like it should?

Would like to hear, thanks in advance.
