### ISSUE TITLE
code.php generates a fatal when creating a new object through a command line script

### ISSUE THREAD

**Issue by Whoeaaah** [Ariadne-CMS/ariadne#15]
Hi,

I have a pinp template that generates new objects. This works fine when calling it from an URL but fatals when running it from a commandline. 

PHP Fatal error:  Call to a member function load() on a non-object in {path to ariadne}/ariadne/lib/widgets/wizard/code.php on line 10

The pinp template runs fine until system.new.phtml is called which includes the code.php file.

Up untill a few weeks ago this worked fine. The recent changes to code.php, submitted on 07-02-2015, seem to be the culprit.

**Comment by mjrider** [comment]
i'm guessing that your cli script doesn't load bootstrap.php
please check https://github.com/Ariadne-CMS/ariadne/blob/master/bin/skeleton.php for an example
if that is not the case, could you supply the code needed to reproduce the issue

**Comment by Whoeaaah** [comment]
Excellent, that is the solution. Thanks.
