### ISSUE TITLE
Scaffolds

### ISSUE THREAD

**Issue by jondor** [Ariadne-CMS/ariadne#16]
Installed the release version 9. First of all congratulations and compliments. It looks good.. 
But as to be expected, the first issues..;-)

Under /system/scaffolds/ I'm should be able to create pprojects which would show up in the scaffold likst when creating a new site project. But..

When I add a pproject::test under /system/scaffolds/muze/ it works. But.. I'm not a muze employee.
When I add a pproject::test under  /system/scaffolds/myscaffolds or under a personal folder
(/system/scaffolds/funsite) they don't show up. 
Which seems a bit more limited than I would expect. 

Related (minor) issue: when I try  to add  the pproject under /system/scaffolds/muze/ the pproject isn't in the typetree. "Show all available types" is needed.

**Comment by poef** [comment]
The documentation is not really clear here, but the idea is that you configure your scaffolds in the config.ini. By default ariadne ships with a single scaffold directory pre-configured under /projects/ and that is the muze scaffolds directory.
To add your own, edit the config.ini on /projects/ or create a config.ini somewhere else and add your directory to it. e.g.

```
<pinp>
    $arConfig = ar::getvar('arConfig');
    $arConfig['settings']['scaffolds'][] = '/system/scaffolds/funsite/';
    ar::putvar('arConfig',$arConfig);
</pinp>
```

**Comment by jondor** [comment]
On Wednesday, May 06, 2015 06:28:37 AM Auke wrote:
> The documentation is not really clear here, but the idea is that you
> configure your scaffolds in the config.ini. By default ariadne ships with a
> single scaffold directory pre-configured under /projects/ and that is the
> muze scaffolds directory. To add your own, edit the config.ini on
> /projects/ or create a config.ini somewhere else and add your directory to
> it. e.g.
> 
> ```
> <pinp>
>     $arConfig = ar::getvar('arConfig');
>     $arConfig['settings']['scaffolds'][] = '/system/scaffolds/funsite/';
>     ar::putvar('arConfig',$arConfig);
> </pinp>
> ```
> 

Hmm.. That means that the system wide scaffolds are defined on pproject level? 
doesn't really sound right to me.  Logically that would work like the local 
user/group/profile in which is makes sense, but for system wide it would be 
more logical if it searched for pprojects to use as scaffold from the 
/system/scaffolds/ level.

The existence of /system/scaffolds/myscaffolds/ seems to indicate that this was 
the original idea in which case a 3th-party folder for scaffolds would also be 
no problem. 

In situations as a shared system between many groups where the owner would 
want to provide some basic site layouts (read: SAAS) it would also make sense.

So while the config.ini makes sense for personal use, it lacks imho in the 
overall picture..

Gerhard

My blog: http://www.funsite.eu/
