### ISSUE TITLE
svn installation issue

### ISSUE THREAD

**Issue by jondor** [Ariadne-CMS/ariadne#4]
When svn support isn't installed, don't offer to turn it on.  The installer hangs, and from there there's basically only one way to get things installed: remove everything, start again and realize that without svn support, you shouldn't turn it on either. 

Also in the installer, some more information on how to install the tar support through pear would be useful.

**Comment by jondor** [comment]
After install you're left at the login screen. Oke, we're not that dense, but what's the username? I do remember giving a password and assume (hope) there was some info on the name also.. but.. being in a hurry to get something running I didn't really notice and now I'm stuck.. Maybe it's an idea to let them choose an login name too?

Oke, I'm in and now I'm lost.. yes I can click around a little, but then? How do I see a site?

Yeah! I managed to get the cat site..  Ah, an link which is going to tell what's available.. a  little much and not a README or DOCU.TXT in sight. What's all this? What should I do with it?  And where's a site which is actually useful and usable? 

Don't get me wrong. This is a major improvement, the OS version of vedor is on the right track and Ariadne has lots of nice new extra's. But those are for the old-time users. 
For a new user there is still an un-climbable learning curve and not real help to get started.

**Comment by poef** [comment]
Agreed, one of the reasons why it is a release candidate. I didn't want to wait untill we had a better welcome screen to show the goodies and get feedback. We will fix that before the final release... So consider this a 'we're working on it'.

**Comment by poef** [comment]
Didn't have the time to fix this for 9.0 release, but will be in 9.1, promise :)

**Comment by mjrider** [comment]
the admin / login screen issue a duplicate for #2
the svn issues is already fixed, which is also the main topic of this issue.
Marking it as closed
