### ISSUE TITLE
SASS support?

### ISSUE THREAD

**Issue by hendriksenremco** [Ariadne-CMS/ariadne#50]
LESS is nice but SASS/SCSS is more broadly used in the community.

Having SASS support would be very much appreciated!

**Comment by poef** [comment]
I found a SCSS compiler written in PHP, https://github.com/leafo/scssphp, but it does need some work. Specifically the import routine assumes it may access the filesystem directly. So for Ariadne we'll need to extend/override the findImport routine in the compiler, I think. I'll try and let you know how that goes.

**Comment by ylebre** [comment]
Not going to do this for now, at least not until we have support for templates that are directly on disk - in that case sass support is just a matter of using it.
