### ISSUE TITLE
Scrolling click offset in detail / icon / list view backend

### ISSUE THREAD

**Issue by kevinmu17** [Ariadne-CMS/ariadne#64]
There is a bug in ariadnes admin/explore.html in all major browsers ( chrome, firefox, safari )

if i select a site with many objects inside ( right window overview ) and scroll a bit down, the pointer isn't clicking where it's suppose to. like there is an offset in the pointer click.

so lets say there are objects called Object001 till Object100 and trying to click on Object066 it's selecting Object044, even when i use the arrow keys to select the right one it's still selecting Object044

This is all working fine UNTIL you scroll down. It doesn't matter if you have List- Detail or Icon view on...

**Comment by mjrider** [comment]
This should be fixed in the latest release

**Comment by kevinmu17** [comment]
nope

**Comment by mjrider** [comment]
could you try to delete your server and browers cache and try again?
i just tried it on my test enviroment, and i select exactly the element i click on
