### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by GaneshKandu** [Ariadne-CMS/ariadne#71]
Hi. Its Ganesh Kandu 
I Trying to install <b>Ariadne-CMS  9.2</b> in My WAMP Server but Getting an Error during Installation 
please Help so that i can install <b>Ariadne-CMS</b>
<ul><li>Warning: include_once(Archive/Tar.php): failed to open stream: No such file or directory in \aria165\lib\modules\mod_tar.phtml on line 18</li>
<li>Warning: include_once(): Failed opening 'Archive/Tar.php' for inclusion (include_path='.;C:\php\pear') in \aria165\lib\modules\mod_tar.phtml on line 18</li>
<li>Fatal error: Class 'PEAR' not found in \aria165\lib\modules\mod_tar.phtml on line 19</li><ul>

**Comment by poef** [comment]
Hi, a bit late, but it looks like a problem with composer. Can you check if the directory 'vendor/pear/archive_tar/Archive/' exists in your ariadne installation and if it contains the Tar.php file?

If so, you can remove line 18 and 19 from mod_tar.phtml, or comment it out, since tar should be now be autoloaded. It looks like we missed a check for the windows installation. The fix will be in the next release, planned for next week ( or earlier)

**Comment by GaneshKandu** [comment]
I have commented line 18,19 from lib\modules\mod_tar.phtml
but its still not working, getting
<b>Fatal error</b>:  Class 'Archive_Tar' not found in <b>lib\modules\mod_tar.phtml</b> on line <b>46</b>
waiting for next release

**Comment by GaneshKandu** [comment]
I have tried on linux also
moved all file and folder of your www folder to ariadne93 folder of my public_html
and remaining to this /home/soft/ariadne93/ folder as privet folder
and renamed my ariadne.inc-unix file to ariadne.inc and updated $ariadne='/usr/local/lib/ariadne/lib'; this line to $ariadne='/home/soft/ariadne93/lib'; 
and gave a writable permission on file and folder on you mention on site
when i am hitting my <mydomain.com>/ariadne93/install/index.php
i am getting error 
<br />
<b>Warning</b>:  require_once(./../../vendor/autoload.php): failed to open stream: No such file or directory in <b>ariadne93/install/index.php</b> on line <b>3</b><br />
<br />
<b>Fatal error</b>:  require_once(): Failed opening required './../../vendor/autoload.php' (include_path='.:/usr/local/apps/php54/lib/php') in <b>ariadne93/install/index.php</b> on line <b>3</b><br />

i dont know what i am doing wrong please suggest

**Comment by mjrider** [comment]
this should be fixed in 9a616d23ae3f3c2e42527fd2443bb9e21aa7cdf7 and will be in the next release
