### ISSUE TITLE
php7 syntax check issues errors

### ISSUE THREAD

**Issue by mjrider** [Ariadne-CMS/ariadne#92]
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; pinp_error has a deprecated constructor in lib/modules/mod_error.php on line 46
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; pinp_selectorIterator has a deprecated constructor in lib/modules/mod_selector.php on line 83
PHP Warning:  Declaration of ar_html_formInputMissing::getLabel() should be compatible with ar_html_formInput::getLabel($label = NULL, $id = NULL, $attributes = NULL) in lib/ar/html/form.php on line 775
PHP Warning:  Declaration of ar_html_formInputMissing::getInput() should be compatible with ar_html_formInput::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL) in lib/ar/html/form.php on line 775
PHP Warning:  Declaration of ar_html_formInputPassword::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL) should be compatible with ar_html_formInputText::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL, $maxlength = NULL, $size = NULL) in lib/ar/html/form.php on line 887
PHP Warning:  Declaration of ar_html_formInputButtonList::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL, $options = NULL) should be compatible with ar_html_formInputSelect::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL, $options = NULL, $multiple = NULL) in lib/ar/html/form.php on line 1154
PHP Warning:  Declaration of ar_html_formInputCheckbox::getField() should be compatible with ar_html_formInput::getField($content = NULL) in lib/ar/html/form.php on line 1220
PHP Warning:  Declaration of ar_html_formInputRadio::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $options = NULL) should be compatible with ar_html_formInputSelect::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL, $options = NULL, $multiple = NULL) in lib/ar/html/form.php on line 1309
PHP Warning:  Declaration of ar_html_formInputHtml::getField() should be compatible with ar_html_formInput::getField($content = NULL) in lib/ar/html/form.php on line 1325
syntax errors found in build
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; pinp_error has a deprecated constructor in lib/modules/mod_error.php on line 46
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; pinp_selectorIterator has a deprecated constructor in lib/modules/mod_selector.php on line 83
Warning: Declaration of ar_html_formInputMissing::getLabel() should be compatible with ar_html_formInput::getLabel($label = NULL, $id = NULL, $attributes = NULL) in lib/ar/html/form.php on line 775
Warning: Declaration of ar_html_formInputMissing::getInput() should be compatible with ar_html_formInput::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL) in lib/ar/html/form.php on line 775
Warning: Declaration of ar_html_formInputPassword::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL) should be compatible with ar_html_formInputText::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL, $maxlength = NULL, $size = NULL) in lib/ar/html/form.php on line 887
Warning: Declaration of ar_html_formInputButtonList::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL, $options = NULL) should be compatible with ar_html_formInputSelect::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL, $options = NULL, $multiple = NULL) in lib/ar/html/form.php on line 1154
Warning: Declaration of ar_html_formInputCheckbox::getField() should be compatible with ar_html_formInput::getField($content = NULL) in lib/ar/html/form.php on line 1220
Warning: Declaration of ar_html_formInputRadio::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $options = NULL) should be compatible with ar_html_formInputSelect::getInput($type = NULL, $name = NULL, $value = NULL, $disabled = NULL, $id = NULL, $title = NULL, $options = NULL, $multiple = NULL) in lib/ar/html/form.php on line 1309
Warning: Declaration of ar_html_formInputHtml::getField() should be compatible with ar_html_formInput::getField($content = NULL) in lib/ar/html/form.php on line 1325

**Comment by mjrider** [comment]
mod_selector and mod_error are fixes in #96

**Comment by ylebre** [comment]
rest is fixed in #134
