### ISSUE TITLE
htmlcleaner removes dashes from tagname

### ISSUE THREAD

**Issue by jondor** [Ariadne-CMS/ariadne#99]
Hi,

While testing with some polymer webcomponent I noticed that that when I add a tag using the backside of Ariadne, (beheer, open pagina, source knop) it strips "-" so

`<hello-world></hello-world> `

goes in and in the page I see

`<hello world></hello>`

which isn't the same at all.. 

This is especially problematic as it seems that the dash is obligatory.. 
[http://webcomponents.org/articles/how-should-i-name-my-element/](http://webcomponents.org/articles/how-should-i-name-my-element/)

**Comment by mjrider** [comment]
the following testcase shows the problem:
```
	public function testTagDash() {
		$html = '<body><hello-world>hello world</hello-world></body>';
		$clean = htmlcleaner::cleanup($html,array());
		$this->assertEquals($html, $clean);
	}
```
